const reasons = [
  'dein Lächeln einfach das allerschönste der Welt ist',
  'ich mich so geborgen bei dir fühle',
  'ich weiß das du der Mensch bist mit den ich den den Rest meines Lebens verbringen möchte',
  'jedes mal wenn du lächelst mein Herz immer schneller schlägt',
  'jeder Tag mit dir ein Geschenk ist',
  'ich alles mit dir machen kann',
  'ich einen echten Gegner in den Sportarten habe xD',
  'du die Einzige bist, bei der ich so sein kann wie ich bin',
  'ich dir jedes Reel schicken kann und es nicht langweilig wird',
  'ich mit dir auch mal wie ein Kind reden kann :D',
  'ich die Art und Weise, wie du mich ansiehst liebe. Als würdest du mich wirklich kennen:)',
  'du mir das Gefühl gibst, dass ich die wichtigste Person auf der ganzen Welt bin',
  'ich mit dir die bekloppten Witze und Sprüche sagen kann und wir trotzdem noch Spaß haben',
  'ich dich ewig durchkitzeln kann',
  'ich mit dir ewig kämpln kann',
  'ich einen kleinen Babypinguin an meiner Seite habe',
  'du die süßeste Stimme hast die es gibt',
  'ich mit dir Abenteuer erleben kann',
  'ich mit dir den besten Sex der Welt habe',
  'ich mit dir so versaut sein kann wie ich will, und du das mitmachst :D',
  'du noch viel verrückter bist als ich',
  'du die schönsten Haare hast',
  'du sooo gut twerken kannst',
  'du mich zum Lächeln bringst, wenn immer ich dich sehe',
  'es einfach das beste Gefühl ist, mit dir zu kuscheln',
  'wir zusammen überall hinfahren können',
  'ich dir alles was in meinem Kopf vorgeht, erzählen kann',
  'ich von Kopf bis Fuß alles an dir liebe - einige Stellen allerdings mehr als die andere :D',
  'du es schaffst mich in dieser verrückten Welt zur Ruhe zu bringen',
  'du dich mit meinen Eltern so gut verstehst',
  'wir auch mal neue Dinge ausprobieren',
  'ich schon jetzt nur noch die Erinnerungen mit dir im Kopf habe',
  'wir uns perfekt ergänzen',
  'du einfach die schönste Stimme der Welt hast',
  'du dich um mich kümmerst, wenn ich krank bin',
  'du Wintersport machst',
  'du so eine harte Schale bei ärgern hast',
  'du einfach so bist wie du bist',
  'du mir die Kraft gibst besser zu werden',
  'du einfach sooo süß aussiehst, wenn du schläfst',
  'ich bei dir so schnell einschlafen kann',
  'du Ziele hast und etwas erreichen willst',
  'wir später super zusammen sein werden',
  'du die beste Mutter für meine Kinder sein wirst, die es gibt',
  'sich deine Fantasien mit meinen vermischen',
  'du mein bester Freund auf der ganzen Welt bist',
  'du mir bei fast allen komplett zuhörst',
  'du versuchst mein Technikzeug zu verstehen',
  'du mich trotzdem noch bei dir hast, auch wenn ich dir manchmal Vorträge über nutzloses halte',
  'du mich auch mal disst',
  'du auch sarkastisch bis und schön konterst',
];
